language: rust
rust:
  - stable
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test
  - cargo test --features reuseport
  - cargo doc --no-deps --all-features
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "PHVT7IaeP5nQQVwGHKwqCYBDp0QyetSlER7se2j2Xgfx+lw3Bu6VWH6VF04B636Gb0tHPN/sUCXSgGRcvDuy6XFOev4LfynoYxNKgHJYg2E34EP2QLwsFfnvE4iujaG3GJk3o935Y7OYGv2OP1HeG4Mv6JhQK0GLnNDBZQ65kWI="

matrix:
  include:
    - rust: beta
    - rust: nightly

notifications:
  email:
    on_success: never
os:
  - linux
  - osx
